In [1]:
# Q1

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from time import time # La libreria expresa el tiempo en segundos!

# Cargar el archivo
dt = [] # Matriz de datos leidos
st = time () # Variable de tiempo

for line in open('iris.data'): # Abre el archivo y hace una pasada por cada línea de este
    dt.append(line.strip().split(',')) # Strip elimina el salto de línea y Split convierte las líneas en una lista
    # print (line.strip().split(',')) # Lista con cada campo puesto como comentario
    # Split (simbolos para separar datos) : puede ser cualquier tipo, no sólo ,
    # print (line) # Lista de valores normales
    
umbral = 100

# X e Y
X = [[float(a) for a in l[0:-1]] for l in dt] # Atributos(numeros)
Y = [l[-1] for l in dt] # Clase (etiqueta en letras)
print ('Tiempo preproceso:', time() - st) # Calcula el tiempo en hacer desde el inicio del script hasta aqui

st = time () # Variable de tiempo

#########################################################################################################################################################
## CLASIFICADOR kNN ###
# En esta clase debemos de poner un parámetro, la K, que indica la cantidad de vecinos utilizados.

neighbours = [1,2,3,4,5,6,7,8,9] # numero de KNeighbours

for k in neighbours: 
    print ('### KNN para',k,'vecinos ###')
    clf = KNeighborsClassifier(k) # Linea a cambiar segun clasificador (entre parentesis se define el valor de la K, que corresponde a la cantidad de vecinos)
    # Lineas iguales para todos:
    clf.fit(X[:umbral], Y[:umbral])
    preds = clf.predict(X[:umbral])

    # Predicciones
    print ('Accuracy:', accuracy_score(Y[:umbral], preds))
    print ('Matriz confusión:')
    print (confusion_matrix(Y[:umbral], preds)) # La matriz compara las dos confusiones y clases, las compara y mira como ha quedado

    # Lo ideal es que el resultado quede todo en las diagonales
    # Cada fila es una clase (cetosa,...)
    # Las columnas indican como los ha clasificado
    # Si sólo hay numeros en la diagonales indica que todos se han clasificado bien. Sino, indica que alguno de los elementos los ha clasificado como uno que realmente no es.
    print ('Tiempo kNN:', time() - st) # Calcula el tiempo que tarda en hacer el kNN


Tiempo preproceso: 0.0007264614105224609
### KNN para 1 vecinos ###
Accuracy: 1.0
Matriz confusión:
[[50  0]
 [ 0 50]]
Tiempo kNN: 0.004271745681762695
### KNN para 2 vecinos ###
Accuracy: 1.0
Matriz confusión:
[[50  0]
 [ 0 50]]
Tiempo kNN: 0.0072515010833740234
### KNN para 3 vecinos ###
Accuracy: 1.0
Matriz confusión:
[[50  0]
 [ 0 50]]
Tiempo kNN: 0.010107278823852539
### KNN para 4 vecinos ###
Accuracy: 1.0
Matriz confusión:
[[50  0]
 [ 0 50]]
Tiempo kNN: 0.012959480285644531
### KNN para 5 vecinos ###
Accuracy: 1.0
Matriz confusión:
[[50  0]
 [ 0 50]]
Tiempo kNN: 0.015815258026123047
### KNN para 6 vecinos ###
Accuracy: 1.0
Matriz confusión:
[[50  0]
 [ 0 50]]
Tiempo kNN: 0.018652915954589844
### KNN para 7 vecinos ###
Accuracy: 1.0
Matriz confusión:
[[50  0]
 [ 0 50]]
Tiempo kNN: 0.02149176597595215
### KNN para 8 vecinos ###
Accuracy: 1.0
Matriz confusión:
[[50  0]
 [ 0 50]]
Tiempo kNN: 0.024339914321899414
### KNN para 9 vecinos ###
Accuracy: 1.0
Matriz confusión:
[[50  0]
 [ 

In [2]:
# Q2

#CARGAMOS DATOS
import numpy as np #importamos la libreria numpy
jain_data = np.loadtxt('jain.txt',dtype=float) #cargamos los datos de housing.data
print('Datos: \n', jain_data)
print('')
print('')

#HACEMOS UN PREPROCESO PARA PREPARAR NUESTROS DATOS
from sklearn import preprocessing #libreria que permite esclar los datos
jain_scl = np.zeros((373,3))            
jain_scaled = preprocessing.scale(jain_data) #escalamos los datos para evitar outliers de valores que sobresalgan mucho respecto a otros
for i in range (3):
    for j in range (373):
        jain_scl[j,i] = round(jain_scaled[j,i],3) #aproximamos a 3 decimales en todos los datos
print('Datos escalados y preprocesados: \n', jain_scl)
print('')
print('')

#DIVIDIR LA MATRIZ 30%-50% PARA EL TRAINING Y EL TEST
from time import time
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score


X = [[float(a) for a in l[0:-1]] for l in jain_scl]
Y = [l[-1] for l in jain_scl]
# separamos los atributos(X) de la clase (Y)

Xf = np.array(X)
Yf = np.array(Y)

# Guardar train y test tanto para los valores de atributos como para la clase
Xtrn, Xtst, Ytrn, Ytst = train_test_split(Xf, Yf, test_size=0.3) # 30% test - 70% training

######## CLASIFICADOR LINEAR REGRESION ##################################################################

reg = linear_model.LinearRegression()
reg.fit(Xtrn, Ytrn)
Ypred = reg.predict(Xtst)

print('######## CALCULOS ########')
print('')

# Coeficientes
print('Coeficientes: \n', reg.coef_)
print('')
# MSE
print('Error Medio Cuadrado: \n', mean_squared_error(Ytst, Ypred))
print('')
# Variancia (cuanto más se acerque a 1 mejor es la predicción)
print('Variancia: \n', r2_score(Ytst, Ypred))
print('')

Datos: 
 [[ 0.85 17.45  2.  ]
 [ 0.75 15.6   2.  ]
 [ 3.3  15.45  2.  ]
 ...
 [38.25 17.35  1.  ]
 [39.5  16.95  1.  ]
 [39.9  17.05  1.  ]]


Datos escalados y preprocesados: 
 [[-2.386  0.804  1.687]
 [-2.396  0.524  1.687]
 [-2.137  0.501  1.687]
 ...
 [ 1.415  0.789 -0.593]
 [ 1.542  0.728 -0.593]
 [ 1.582  0.743 -0.593]]


######## CALCULOS ########

Coeficientes: 
 [-0.31316107  0.68490254]

Error Medio Cuadrado: 
 0.33127510085995227

Variancia: 
 0.5655524792340743



In [ ]:
# Q4

#CARGAMOS DATOS
import numpy as np #importamos la libreria numpy
file_data = np.loadtxt('ponemos el archivo de datos a cargar aqui',dtype=definir el tipo de datos que contine) #cargamos los datos de housing.data


#HACEMOS UN PREPROCESO PARA PREPARAR NUESTROS DATOS (solo si tenemos valores que se salen del rango común)
from sklearn import preprocessing #libreria que permite esclar los datos
file_scl = np.zeros((filas de datos,columnas de datos))            
file_scaled = preprocessing.scale(file_data) #escalamos los datos para evitar outliers de valores que sobresalgan mucho respecto a otros
for i in range (columnas de datos):
    for j in range (filas de datos):
        file_scl[j,i] = round(file_scaled[j,i],3) #aproximamos a 3 decimales en todos los datos
        

#DIVIDIR LA MATRIZ X%-Y% PARA EL TRAINING Y EL TEST
from time import time
from sklearn.model_selection import train_test_split

X = [[float(a) for a in l[0:-1]] for l in file_scl]
Y = [l[-1] for l in file_scl]
# separamos los atributos(X) de la clase (Y)

Xf = np.array(X)
Yf = np.array(Y)

# Guardar train y test tanto para los valores de atributos como para la clase
Xtrn, Xtst, Ytrn, Ytst = train_test_split(Xf, Yf, test_size=poner % de test que se quiere) # X% test - Y% training

In [9]:
# Q5

#CARGAMOS DATOS
import numpy as np #importamos la libreria numpy
jain_data = np.loadtxt('jain.txt',dtype=float) #cargamos los datos de housing.data
print('Datos: \n', jain_data)
print('')
print('')

#HACEMOS UN PREPROCESO PARA PREPARAR NUESTROS DATOS
from sklearn import preprocessing #libreria que permite esclar los datos
jain_scl = np.zeros((373,3))            
jain_scaled = preprocessing.scale(jain_data) #escalamos los datos para evitar outliers de valores que sobresalgan mucho respecto a otros
for i in range (3):
    for j in range (373):
        jain_scl[j,i] = round(jain_scaled[j,i],3) #aproximamos a 3 decimales en todos los datos
print('Datos escalados y preprocesados: \n', jain_scl)
print('')
print('')

#DIVIDIR LA MATRIZ 50%-50% PARA EL TRAINING Y EL TEST
from time import time
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC


X = [[float(a) for a in l[0:-1]] for l in jain_scl]
Y = [l[-1] for l in jain_scl]
# separamos los atributos(X) de la clase (Y)

Xf = np.array(X)
Yf = np.array(Y)

# Guardar train y test tanto para los valores de atributos como para la clase
Xtrn, Xtst, Ytrn, Ytst = train_test_split(Xf, Yf, test_size=0.5) # 30% test - 70% training

def clasificacion(clf):
    st = time()
    clf.fit(Xtrn, Ytrn)
    preds = clf.predict(Xtst).tolist()

    ### evaluación ###
    print('Accuracy:', accuracy_score(Ytst, preds)*100,'%')
    print('Matriz confusion:')
    print(confusion_matrix(Ytst, preds))
    print('Tiempo:', time() - st)
    
######## CLASIFICADOR SVM ##################################################################

print('#########################')
print('SVC Lineal:')
clasificacion(SVC)

Datos: 
 [[ 0.85 17.45  2.  ]
 [ 0.75 15.6   2.  ]
 [ 3.3  15.45  2.  ]
 ...
 [38.25 17.35  1.  ]
 [39.5  16.95  1.  ]
 [39.9  17.05  1.  ]]


Datos escalados y preprocesados: 
 [[-2.386  0.804  1.687]
 [-2.396  0.524  1.687]
 [-2.137  0.501  1.687]
 ...
 [ 1.415  0.789 -0.593]
 [ 1.542  0.728 -0.593]
 [ 1.582  0.743 -0.593]]


#########################
SVC Lineal:


TypeError: fit() missing 1 required positional argument: 'y'